[project]
name = "mcp-crypto-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ccxt>=4.4.73",
    "fastmcp>=0.4.1",
    "feedparser>=6.0.11",
    "psycopg[binary]>=3.2.6",
    "pydantic>=2.11.3",
]

[tool.ruff]
target-version = "py311"
line-length = 100
# 包含推荐的规则集
select = [
    "E",   # pycodestyle 错误
    "F",   # pyflakes
    "I",   # isort
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
    "ARG", # flake8-unused-arguments
    "ERA", # eradicate
    "PL",  # pylint
]

[tool.ruff.format]
# 使用双引号 - 这是Python社区当前的主流选择
quote-style = "double"

[tool.mypy]
python_version = "3.11"
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "ruff>=0.11.4",
    "types-psycopg2>=2.9.21.20250318",
    "types-pyyaml>=6.0.12.20250402",
    "types-requests>=2.32.0.20250328",
    "types-setuptools>=78.1.0.20250329",
]
